server:
  port: 9004
spring:
  application:
    name: alibaba-nacos-gateway
  cloud:
     nacos:
        discovery:
           server-addr: 192.168.174.128:8848

     gateway:
       discovery:
         locator:
           enabled: true
         routes:
         - id: 1
           uri: lb://service-consumer
           predicates:
            - Method=GET,POST
            - Header=X-Request-Id, \d+