
spring:
  application:
    name: dubbo-consumer2

demo:
  service:
    version: 1.0.0

nacos:
  host: 192.168.174.128
  port: 8848

dubbo:
  registry:
    address: nacos://${nacos.host}:${nacos.port}
server:
  port: 8033
